"""update bikes with new fields

Revision ID: d427c003fc67
Revises: d58052c7b7be
Create Date: 2026-03-30 17:07:03.971647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd427c003fc67'
down_revision: Union[str, Sequence[str], None] = 'd58052c7b7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            UPDATE bikes
            SET bike_type = :bike_type,
                frame_material = :frame_material,
                frame_size = :frame_size,
                frame_size_label = :frame_size_label,
                wheel_size = :wheel_size,
                tire_width = :tire_width,
                gear_count = :gear_count,
                brake_type = :brake_type,
                suspension_type = :suspension_type,
                color = :color,
                weight_kg = :weight_kg,
                recommended_height_min = :recommended_height_min,
                recommended_height_max = :recommended_height_max,
                usage = :usage,
                target_user = :target_user
            WHERE name = :name
        """),
        [
            {
                "name": "Trek Marlin 7",
                "bike_type": "MOUNTAIN",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 29,
                "tire_width": 2.25,
                "gear_count": 12,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "GREY",
                "weight_kg": 14.80,
                "recommended_height_min": 165,
                "recommended_height_max": 180,
                "usage": "TRAIL",
                "target_user": "INTERMEDIATE",
            },
            {
                "name": "Scott Scale 970",
                "bike_type": "MOUNTAIN",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 29,
                "tire_width": 2.20,
                "gear_count": 12,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "BLACK",
                "weight_kg": 13.20,
                "recommended_height_min": 168,
                "recommended_height_max": 182,
                "usage": "SPORT",
                "target_user": "INTERMEDIATE",
            },
            {
                "name": "Klein Attitude",
                "bike_type": "MOUNTAIN",
                "frame_material": "STEEL",
                "frame_size": 19,
                "frame_size_label": "L",
                "wheel_size": 26,
                "tire_width": 2.10,
                "gear_count": 9,
                "brake_type": "MECHANICAL_DISC",
                "suspension_type": "FRONT",
                "color": "RED",
                "weight_kg": 15.90,
                "recommended_height_min": 175,
                "recommended_height_max": 190,
                "usage": "TRAIL",
                "target_user": "BEGINNER",
            },
            {
                "name": "Olympia City Line",
                "bike_type": "CITY",
                "frame_material": "ALUMINIUM",
                "frame_size": 15,
                "frame_size_label": "S",
                "wheel_size": 28,
                "tire_width": 1.75,
                "gear_count": 7,
                "brake_type": "V_BRAKE",
                "suspension_type": "NONE",
                "color": "BLUE",
                "weight_kg": 16.30,
                "recommended_height_min": 155,
                "recommended_height_max": 170,
                "usage": "COMMUTING",
                "target_user": "BEGINNER",
            },
            {
                "name": "Trek FX 3",
                "bike_type": "TREKKING",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 28,
                "tire_width": 1.60,
                "gear_count": 18,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "NONE",
                "color": "WHITE",
                "weight_kg": 11.40,
                "recommended_height_min": 168,
                "recommended_height_max": 182,
                "usage": "TOURING",
                "target_user": "INTERMEDIATE",
            },
            {
                "name": "Giant Talon 1",
                "bike_type": "MOUNTAIN",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 29,
                "tire_width": 2.25,
                "gear_count": 10,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "BLUE",
                "weight_kg": 14.50,
                "recommended_height_min": 168,
                "recommended_height_max": 182,
                "usage": "TRAIL",
                "target_user": "INTERMEDIATE",
            },
            {
                "name": "KTM Ultra 1964",
                "bike_type": "MOUNTAIN",
                "frame_material": "ALUMINIUM",
                "frame_size": 19,
                "frame_size_label": "L",
                "wheel_size": 29,
                "tire_width": 2.20,
                "gear_count": 12,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "BLACK",
                "weight_kg": 13.40,
                "recommended_height_min": 175,
                "recommended_height_max": 190,
                "usage": "SPORT",
                "target_user": "ADVANCED",
            },
            {
                "name": "Felt Verza Speed 50",
                "bike_type": "CITY",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 28,
                "tire_width": 1.50,
                "gear_count": 18,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "NONE",
                "color": "GREY",
                "weight_kg": 11.90,
                "recommended_height_min": 165,
                "recommended_height_max": 180,
                "usage": "COMMUTING",
                "target_user": "BEGINNER",
            },
            {
                "name": "Devinci Marshall",
                "bike_type": "MOUNTAIN",
                "frame_material": "ALUMINIUM",
                "frame_size": 19,
                "frame_size_label": "L",
                "wheel_size": 29,
                "tire_width": 2.40,
                "gear_count": 12,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FULL",
                "color": "ORANGE",
                "weight_kg": 15.20,
                "recommended_height_min": 175,
                "recommended_height_max": 192,
                "usage": "TRAIL",
                "target_user": "ADVANCED",
            },
            {
                "name": "Yuba Kombi",
                "bike_type": "CITY",
                "frame_material": "STEEL",
                "frame_size": 19,
                "frame_size_label": "L",
                "wheel_size": 26,
                "tire_width": 2.10,
                "gear_count": 8,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "NONE",
                "color": "GREEN",
                "weight_kg": 26.50,
                "recommended_height_min": 170,
                "recommended_height_max": 195,
                "usage": "COMMUTING",
                "target_user": "BEGINNER",
            },
            {
                "name": "Corratec E-Power X Vert",
                "bike_type": "ELECTRIC",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 29,
                "tire_width": 2.25,
                "gear_count": 10,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "WHITE",
                "weight_kg": 23.80,
                "recommended_height_min": 168,
                "recommended_height_max": 185,
                "usage": "COMMUTING",
                "target_user": "BEGINNER",
            },
            {
                "name": "Trek Domane AL 2",
                "bike_type": "ROAD",
                "frame_material": "ALUMINIUM",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 28,
                "tire_width": 1.10,
                "gear_count": 16,
                "brake_type": "RIM",
                "suspension_type": "NONE",
                "color": "BLACK",
                "weight_kg": 9.90,
                "recommended_height_min": 168,
                "recommended_height_max": 182,
                "usage": "TOURING",
                "target_user": "INTERMEDIATE",
            },
            {
                "name": "Scott Sub Cross 30",
                "bike_type": "TREKKING",
                "frame_material": "ALUMINIUM",
                "frame_size": 19,
                "frame_size_label": "L",
                "wheel_size": 28,
                "tire_width": 1.75,
                "gear_count": 18,
                "brake_type": "HYDRAULIC_DISC",
                "suspension_type": "FRONT",
                "color": "BLUE",
                "weight_kg": 13.80,
                "recommended_height_min": 175,
                "recommended_height_max": 190,
                "usage": "TOURING",
                "target_user": "BEGINNER",
            },
            {
                "name": "Klein Pulse",
                "bike_type": "MOUNTAIN",
                "frame_material": "STEEL",
                "frame_size": 17,
                "frame_size_label": "M",
                "wheel_size": 26,
                "tire_width": 2.10,
                "gear_count": 9,
                "brake_type": "MECHANICAL_DISC",
                "suspension_type": "FRONT",
                "color": "RED",
                "weight_kg": 15.40,
                "recommended_height_min": 165,
                "recommended_height_max": 180,
                "usage": "TRAIL",
                "target_user": "BEGINNER",
            },
            {
                "name": "Olympia Voyager",
                "bike_type": "CITY",
                "frame_material": "ALUMINIUM",
                "frame_size": 15,
                "frame_size_label": "S",
                "wheel_size": 28,
                "tire_width": 1.75,
                "gear_count": 7,
                "brake_type": "V_BRAKE",
                "suspension_type": "NONE",
                "color": "PURPLE",
                "weight_kg": 16.10,
                "recommended_height_min": 155,
                "recommended_height_max": 170,
                "usage": "COMMUTING",
                "target_user": "BEGINNER",
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            UPDATE bikes
            SET bike_type = NULL,
                frame_material = NULL,
                frame_size = NULL,
                frame_size_label = NULL,
                wheel_size = NULL,
                tire_width = NULL,
                gear_count = NULL,
                brake_type = NULL,
                suspension_type = NULL,
                color = NULL,
                weight_kg = NULL,
                recommended_height_min = NULL,
                recommended_height_max = NULL,
                usage = NULL,
                target_user = NULL
            WHERE name = :name
        """),
        [
            {"name": "Trek Marlin 7"},
            {"name": "Scott Scale 970"},
            {"name": "Klein Attitude"},
            {"name": "Olympia City Line"},
            {"name": "Trek FX 3"},
            {"name": "Giant Talon 1"},
            {"name": "KTM Ultra 1964"},
            {"name": "Felt Verza Speed 50"},
            {"name": "Devinci Marshall"},
            {"name": "Yuba Kombi"},
            {"name": "Corratec E-Power X Vert"},
            {"name": "Trek Domane AL 2"},
            {"name": "Scott Sub Cross 30"},
            {"name": "Klein Pulse"},
            {"name": "Olympia Voyager"},
        ],
    )
